# Generated by Django 5.1.2 on 2024-10-18 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cupones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cupon",
            name="titulo",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
